safe: true
source: .
destination: ./_site
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache']
sass:
  style: uncompressed

url: https://future-proof-iot.github.io/PSAR
baseurl: https://future-proof-iot.github.io/PSAR/

#deadlines:
#- name: Registration
#  date: May 17, 2020
#- name: IEEE EuroS&P RIOT Tutorial
#  date: June 19, 2020

# Configuration for site
title: PSAR
description: Physical Security Applied to (R)IOT
author: Inria
email:
logo: images/RIOT-logo.png

responsive_bp: 768

permalink: /:page.html

navbar_list:
- name: Home
  link: /
#- name: About
#  link: about
#- name: Activity
#  link: events
#- name: Partners
#  link: partners
- name: Contact
  link: contact
#- name: Registration
#  link: https://www.ieee-security.org/TC/EuroSP2020/

# Configuration for asides.html
asides:
  github: false
  #links: true
  # tweets: false

# google_analytics:
#    account: UA-XXXXX-X

# google_plus_one:
#   size: medium

# twitter:
#   username: ?
#   count: 5
#   exclude_replies: true
#   show_screen_name: true
#   show_follower_count: false
#   widget_id: ?

github:
   username: future-proof-iot
   count: 10
